name: simple-reverse-proxy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build & push Image
        uses: actions/checkout@v2
      
      - name: Login to dockerhub 
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKERPW }}
          username: cleowoman
      
      - name: Set up docker build
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: cleowoman/simple-reverse-proxy:v007
